name: pusht_image

image_shape: &image_shape [3, 128, 128]

shape_meta: &shape_meta
  # acceptable types: rgb, low_dim
  obs:
    image1:
      shape: ${task.image_shape}
      type: rgb

    image2:
      shape: ${task.image_shape}
      type: rgb
   
    agent_pos:
      shape: [2]
      type: low_dim
  action: 
    shape: [2]

# env_runner:
  # _target_: diffusion_policy.env_runner.real_pusht_image_runner.RealPushTImageRunner

env_runner:
  _target_: diffusion_policy.env_runner.pusht_3d_image_runner.Pusht3DImageRunner
  n_train: 1
  n_train_vis: 0
  train_start_seed: 0
  n_test: 0
  n_test_vis: 0
  legacy_test: False
  test_start_seed: 100000
  max_steps: 300
  n_obs_steps: ${n_obs_steps}
  n_action_steps: ${n_action_steps}
  fps: 10
  past_action: ${past_action_visible}
  n_envs: null

dataset:
  _target_: diffusion_policy.dataset.pusht_image_3dsim_maniskill_dataset.PushtImageDatasetManiSkill
  zarr_path: data/pusht_3d/20240817_100620
  horizon: ${horizon}
  pad_before: ${eval:'${n_obs_steps}-1'}
  pad_after: ${eval:'${n_action_steps}-1'}
  seed: 42
  val_ratio: 0.02
  max_train_episodes: 90
